### ISSUE TITLE
How do I get the CACHE-source as in the video tutorial?

### ISSUE THREAD

**Issue by edmondyang81** [torinmb/mediapipe-touchdesigner#105]
I am trying to get overlay of the initial source back and comped, but I can get seem to get two sources of webcam.

Seem I need SpoutOut somehow? But my VideoIn cant be on two places at same time anyhow?

**Comment by domisjustanumber** [comment]
If you follow these instructions, your network should then be Video Device In TOP > Spout Out > SpoutCam > MediaPipe.

You can use the example network in the MediaPipe.toe project
