### ISSUE TITLE
Unable to get MediaPipe TouchDesigner.toe working

### ISSUE THREAD

**Issue by bgigurtsis** [torinmb/mediapipe-touchdesigner#108]
Hey all,

Trying to get this plugin working for the first time. Here's what I see when I start it up: 

![image](https://github.com/user-attachments/assets/d8d0fb2a-6f37-43db-829c-8fb248e07994)

I have:

1. Been using Touchdesigner 2023.12000, Windows 10 64bit. 
2. Registered SpoutCam64 with my webcam setttings (1280 x 720, LifeCam HD-3000). No other program is using my webcam.
3. For videodevin1 I selected my webcam. This shows up fine.
4. Selected SpoutCam as the Webcam for my MediaPipe, heres what it shows:

![image](https://github.com/user-attachments/assets/a59a5d85-ad0f-4b1e-afee-dd6702ba1cf7)

Here are my SpoutCam settings:

![image](https://github.com/user-attachments/assets/7ccb949e-71db-4361-b6b7-a0558d3810db)

Additionally, all components like hand tracking show errors

![image](https://github.com/user-attachments/assets/655abcfb-9b84-43fa-87ff-84719775b547)

Lastly, I tried creating a completely separate videodevin2 for testing with the SpoutCam as the device, while the videodevin1 with my webcam is running, and that works perfectly. So that leads me to believe that SpoutCam itself must be working in some capacity!

I'm sure im missing something stupid - any help is greatly appreciated.

**Comment by domisjustanumber** [comment]
You need to unzip all the files and toxes folders from the release.zip for the project to load properly.

**Comment by bgigurtsis** [comment]
Yep, totally clicked download on the wrong file. Thanks!
