### ISSUE TITLE
Object detection filtering

### ISSUE THREAD

**Issue by kefon** [torinmb/mediapipe-touchdesigner#111]
Hi there,
First, thank you for your amazing work! Your plugin is amazing and I can't stop playing with it! I'm currently testing different approaches for object detection, and your implementation seems to be a pretty solid one! 

For now I'm struggling finding the correct way to filter the categories I want to detect in the object detection part. I want to track only the persons. I know you can add a parameter in the Object detection task to filter what is to be detected (using 'category_allowlist') but so far I can't understand how to set it in mediapipe... 

The fast and easy tweak I found it to simply filter the results JSON in the 'object_tracking' op. I'm sure there is a more optimized way to do it as for now the media pipe is trying to detect everything, and I'm filtering the results. Is it possible to provide the "category_allowlist=['person']" parameter directly to the mediapipe instead of detecting everything and then filter the results?

Thanks in advance for your help!

**Comment by domisjustanumber** [comment]
Hey @kefon glad you're having fun with the plugin!

While you can supply filters to the object detector into MediaPipe, I believe it just filters the detection results in the JS module - it doesn't actually speed up performance of the model doing the detection, as the model is always detecting everything.

Your solution is one option, or you can filter the output table DAT from the object_tracking component - deleting parts in that component that you're not using will likely have an impact to speed things up.

The probe in the Palette is a great way to take a look around to see what's taking the most time to process.

**Comment by kefon** [comment]
Thanks a lot @domisjustanumber for your quick answer. Ok I understand, I suspected that (as I have the same process using another model with a Oak-D) but I wanted to be sure not to miss anything. I will try the DAT filtering approach.
Thanks again!
