### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by Uomosupernova** [torinmb/mediapipe-touchdesigner#26]
Hi guys! First of all, thank you for your work on TD: I have followed you for 2 years on YT.

I have an issue with this plugin. I'm using Windows 10 with the new release built of TD: 2023.10130.
In the dropdown menu for the webcam, it isn't visible the HD Camera of the PC (MSI GP75 Leopard) and also the MediaPipe component presents a red cross:
![1](https://github.com/torinmb/mediapipe-touchdesigner/assets/144531225/2dd620a2-d9af-4e28-a123-40d9f5a11209)
Inside the component the issue is this: 
![2](https://github.com/torinmb/mediapipe-touchdesigner/assets/144531225/f0379522-b894-4dda-894a-10226aca58dc)

How can I fix this? 

Thanks for your time ;)

**Comment by torinmb** [comment]
Hey! @Uomosupernova So far this has only been tested on the latest stable build of TouchDesigner 2022.33910
try running it on that version

**Comment by domisjustanumber** [comment]
Hi @Uomosupernova it looks like you downloaded the source.zip, which is for making changes to the source code and doesn't run on it's own.

If you download the release.zip fromhttps://github.com/torinmb/mediapipe-touchdesigner/releases/tag/v0.2.1

It should work, but let us know if it doesn't

**Comment by domisjustanumber** [comment]
I'm going to close this one to tidy things up, but please re-open it if you still need things
