### ISSUE TITLE
endless loading

### ISSUE THREAD

**Issue by brianvanmontfoort** [torinmb/mediapipe-touchdesigner#29]
Hi, thanks for all this work. Unfortunately I can't get the Spoutcam option in the Mediapipe container as webcam.  When using the moviefile in TOP, and no webcam, also nothing happens.  
I found this warning:
![image](https://github.com/torinmb/mediapipe-touchdesigner/assets/48725569/911b9ed3-d182-421f-9ffc-93d7eb3e8723)

**Comment by domisjustanumber** [comment]
Hi @brianvanmontfoort it looks like you may have the development version.

Can you confirm if you are using the release.zip file from the releases page? https://github.com/torinmb/mediapipe-touchdesigner/releases/tag/v0.2.1

**Comment by brianvanmontfoort** [comment]
![image](https://github.com/torinmb/mediapipe-touchdesigner/assets/48725569/90955671-e0b2-4f52-accf-0dd0befdc1a6)

Yes, started the .toe from the release.zip

**Comment by brianvanmontfoort** [comment]
That was the solution! Many thanks!!!
