### ISSUE TITLE
Open the plugin normally, but there is a black edge on the right side of the camera, help!

### ISSUE THREAD

**Issue by leozongmac** [torinmb/mediapipe-touchdesigner#31]
Hello, everyone.
My plug-in can open normally, but there will be a black area on the right side, how to solve it?
System: MAC M1 PRO

<img width="1615" alt="截屏2023-09-13 11 13 24" src="https://github.com/torinmb/mediapipe-touchdesigner/assets/93966670/c54aa0bc-e457-4761-b56b-a0e37f38e4ed">

**Comment by domisjustanumber** [comment]
Hi @leozongmac

It looks like the whole image is offset. Currently the plugin only works with 1280 x 720p video. Can you confirm the MediaPipe component is still set to that size?

**Comment by domisjustanumber** [comment]
It's been a couple of weeks, so I'm going to close this for now, but please reopen if you need more help.

**Comment by minnie427** [comment]
I'm having a same issue with my iMac, it works find with my mac book though.. Any solutions to this yet?  I haven't changed any resolution setting in the mediapipe
