### ISSUE TITLE
Loads up but doesnt work

### ISSUE THREAD

**Issue by amannn17** [torinmb/mediapipe-touchdesigner#32]
I tried all the troubleshooting methods I could find, but none of them seemed to help. My TD version is 2022.33910. I registered & unregistered on Spoutcam as directed in the tut as well. I also tried changing the port to 3002, but no good. My webcam and internet connection are fine. I tried checking Spoutcam on the Mediapipe website and it worked fine. My starting res is 1280 x 720 as mentioned.

I hope the screenshots help you find out the issue. Really excited to use the plugin.

<img width="1230" alt="err7" src="https://github.com/torinmb/mediapipe-touchdesigner/assets/132589184/c5a01735-5036-409b-9205-dfa097a7a1da">
<img width="1246" alt="err6" src="https://github.com/torinmb/mediapipe-touchdesigner/assets/132589184/06749ad5-eb4d-4eb0-992c-cfbb6d6205d0">
<img width="1911" alt="err5" src="https://github.com/torinmb/mediapipe-touchdesigner/assets/132589184/412bf02d-39ec-469a-8138-adb16dbe5073">
<img width="1911" alt="err4" src="https://github.com/torinmb/mediapipe-touchdesigner/assets/132589184/e8cc5a37-efff-44f5-a6f0-c05e204df3b1">
<img width="598" alt="err8" src="https://github.com/torinmb/mediapipe-touchdesigner/assets/132589184/4733f36e-b3b7-43b2-84bd-1e6201f6a734">

thanks!

**Comment by domisjustanumber** [comment]
Hi @amannn17 thanks for all the info. Can you confirm the VideoDeviceIn that you're sending the SyphonSpoutOut is also 1280x720? It looks like it may be SD in the screenshot and that could be your issue.

**Comment by domisjustanumber** [comment]
I'm going to close this one to tidy things up, but please re-open it if you still need things
