### ISSUE TITLE
SpoutCam not showing

### ISSUE THREAD

**Issue by georgfruth** [torinmb/mediapipe-touchdesigner#33]
Hi Torin, Hi Dom, such a great work!!! I have a problem: SpoutCam is not showing in the webcam menu. I have downloaded the newest versions etc. I am on PC windows 10. What can I have done wrong? thank you soooo much!!!!!

**Comment by georgfruth** [comment]
Is it necessary to be online in order to run it properly?

**Comment by domisjustanumber** [comment]
Hi @georgfruth thanks for the kind words!

You don't need to be online at all for this to work, but it does use a local network port. It's possible you have something else running already, so you could try changing the MediaPipe port from 3001 to something else (3002 should do it).

If that doesnt work, if you can open the text port with Ctrl T and post a screenshot of what it says that will help figure out what is going on

**Comment by georgfruth** [comment]
Thank you Dom for your quick reply. Changing the port did not help. I have now installed touchdesigner on windows 11 and here spoutcam works and is now also selectable in the dropd
own menu. However, the mediapipe window shows RGB noise. Nothing is recognised. If I select the webcam (RAPOO no matter what resolution) in the dropdown menu, the mediapipe window is black. What could be the reason for this? Greetings George
<img width="920" alt="Screenshot_TD_mediapipe" src="https://github.com/torinmb/mediapipe-touchdesigner/assets/60230120/9cc021d3-525d-4383-9a70-bcade8164d6d">

**Comment by domisjustanumber** [comment]
Hmm thanks for the extra info. My guess is this is possibly a resolution issue. Currently the plugin only works at 1280 x 720 - can you confirm your camera supports that resolution, and the VideoDevice In TOP that sends the video to the SyphonSpoutout TOP is set to 1280 x 720 as well?

**Comment by georgfruth** [comment]
Hi Dom, it's exactly 1280 x 720 30fps
In the Spout register window, as in TD

**Comment by domisjustanumber** [comment]
Well this is a strange one indeed.

When you select your webcam as the source in the MediaPipe component, are you also deleting/disabling the VideoDeviceIn TOP? On my laptop I can only have my webcam used by 1 thing at a time, so if I have my webcam running in the VideoDeviceIn TOP it blocks MediaPipe from being able to use the webcam as a source.

**Comment by georgfruth** [comment]
Hi dom, I'm sorry, I had a typo in the spout register window. It works! I am sooo happy! I can select the webcam in the mediapipe container while it is running in the videodevin. However, the picture in the mediapipe window is then black. With spoutcam it works though. Now I have to send you money :) this is really a great thing

**Comment by georgfruth** [comment]
One question, is it possible to lower the resolution for mediapipe to process everything and combining the overlays with a higher resolution image later?

**Comment by georgfruth** [comment]
And is it possible to capture poses of more than one person?

**Comment by domisjustanumber** [comment]
Yeah, you could do that - if you add a transform TOP after the Video Device In TOP you can send the resized 720p version to Spout Out, and use the 1080p (or 2k or whatever) version in the rest of your project. I'd suggest piping the source resolution image into the cache in the example project so it can get re-synced with the output of MediaPipe. That cache TOP accounts for the few frames of delay that MediaPipe has doing all the detection work.

Currently MediaPipe can only detect the poses of 1 person, but I suspect there will be improvements to that down the road, and we'll try and implement them once Google release those updates.
