### ISSUE TITLE
Facetracking translate error xForm MATRIX

### ISSUE THREAD

**Issue by duhglobe** [torinmb/mediapipe-touchdesigner#35]
The tool is incredible. 
With my team we are implementing it right now and we are trying to take it to a festival in France for an installation!
///
I'm having problems, despite having followed the whole walkthrough and tutorial, to use facetracking_ to track the full movement of the head. It seems to only take rotation and not translation and position. Attached is a short video of the error I got stuck in. 

Thank you in advance for your support!!!
Andrea

https://github.com/torinmb/mediapipe-touchdesigner/assets/117079301/80fbf3ef-622c-4d17-8db4-e7c449261f95

**Comment by domisjustanumber** [comment]
Hi @duhglobe love that you're making use of this!

I have to admit I don't fully understand the transformation matrix either, but I have been able to get it to work in 3D space with a SOP.

If you take a look at the `face_filter_example` and the SOP example, you can see how it works.
1. Disable the Pre-Transform for the `canonical_face_model` geo (`geo3`) and your object (`geo4`)
2. Use the `canonical_face_model` to align your 3D object to the face that will be detected. If you want to map a 2D object to the face, use the TOP as a texture for a Rectangle SOP (see my video).
3. When you have the `canonical_face_model` and your object aligned, enable the Pre-Transform for your object and it should map correctly.

The translation works pretty well as long as you don't move too close to the edge of the frame (you see it stop working if I get too close to the camera). It might work best if you track a wide shot from the camera, then crop to a smaller size after tracking.

https://youtu.be/_m4zNzKxkxg

**Comment by duhglobe** [comment]
[SOLVED]
Thank you very much.

Stupidly after doing a thousand double checks everywhere I thought the problem might be for some reason related to the size of the 3D model I had imported... often FBXs are strange for me to handle. Apparently it was gigantic... but somehow the Matrix DAT still managed to fit it to the frame and make it fit but being huge the x and y axis movement equalled millimetres and the mask stayed still. 

**Reminder*** always check the size of your model with Geometry View...

Cheers <3
