### ISSUE TITLE
Object detection Touchdesigner bounding boxes not aligned

### ISSUE THREAD

**Issue by mikebru** [torinmb/mediapipe-touchdesigner#36]
I noticed while using the object detection portion of the TOX that the bounding boxes that Touchdesginer is drawing do not align with bounding boxes that Mediapipe is drawing. They are offset and don't accurately map back onto the video. 

Thanks for putting this resource together, it is a really great tool and addition to touchdesigner!

**Comment by domisjustanumber** [comment]
Hi @mikebru thanks for letting us know - we'll take a look at the code and see what's going on.

**Comment by mettapana** [comment]
I also observe the same thing here. It doesn't look like a translation or scaling problem in instance space. It seems that the objects are in other positions randomly.

I am great to see the possibility of using mediapipe in TD. Thanks for this project.

**Comment by benjavides** [comment]
I noticed the same using the current last release (v0.3.2)

**Comment by domisjustanumber** [comment]
I spent a few hours this week fixing up all the bounding boxes for the object tracking and added them for the face tracking too.

The changes are all checked in, so will be there next time we do a release build.

**Comment by domisjustanumber** [comment]
This fix got released in [v0.3.3](https://github.com/torinmb/mediapipe-touchdesigner/releases/tag/v0.3.3) so closing this issue :)
