### ISSUE TITLE
Incorrect MimeType preventing javascript from loading on some machines

### ISSUE THREAD

**Issue by mikebru** [torinmb/mediapipe-touchdesigner#37]
Hey there! 

I was testing on a few different computers and noticed that on some PCs Mediapipe wouldn't load. 

From taking a look at the webpage I saw that this error was occurring, 

`Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.`

I went into the Mediapipe tox and added these lines of code in the mp_webserver_callbacks dat.

`	if fileName.endswith('.js'):
			mimeType = ['application/javascript']
	else:
		mimeType = mimetypes.guess_type(fileName, strict=False)
`

This solved the issue for me and allowed the TOX to function correctly.

![image](https://github.com/torinmb/mediapipe-touchdesigner/assets/32722658/2d3e57bd-b60a-4102-9870-7b6147f4fb7b)

**Comment by domisjustanumber** [comment]
Ohhhh thanks for that gem of info @mikebru ! That would explain why so many people seem to be having issues with the web page randomly not loading, we'll put that change into the next release!

@torinmb - FYI

**Comment by torinmb** [comment]
Great fix! Just published a new release that incorporates this :)
https://github.com/torinmb/mediapipe-touchdesigner/releases/tag/v0.2.2
