### ISSUE TITLE
Media Pipe won't find webcams

### ISSUE THREAD

**Issue by bsnigur1** [torinmb/mediapipe-touchdesigner#38]
Hey. I've set up Media Pipe on 2 PC's now. I am trying to set it up on one more, but the MediaPipe tox webcams are updating. I have Spoutcam setup and everything, but the webcams scroll down doesn't change. I've tried a bunch of fixes, but none have worked.

**Comment by domisjustanumber** [comment]
Hi @bsnigur1, it looks like someone just found a solution to this issue - if you follow the instructions in this issue, does it solve your issue as well? https://github.com/torinmb/mediapipe-touchdesigner/issues/37

**Comment by bsnigur1** [comment]
@domisjustanumber legend, thank you. Worked like a charm.

**Comment by domisjustanumber** [comment]
Amazing, thanks for letting me know!
