### ISSUE TITLE
OFFLINE mediapipe.tox everytime I re-open the project.

### ISSUE THREAD

**Issue by duhglobe** [torinmb/mediapipe-touchdesigner#39]
It only happens to me that every time I close a project then when I reopen it MediaPipe.tox is offline with a red cross and also the related tool (facetracking for example)?. Is there a way, maybe saving everything in the same folder, MediaPipe.tox etc. included (?) but I have already tried and every time I restart I have to delete the old nodes and replace them .

Thank u in advantage <3
Love u guys
Andrea

![Screenshot 2023-09-24 at 01 43 52](https://github.com/torinmb/mediapipe-touchdesigner/assets/117079301/1c6dfdb6-e665-4a69-a112-6875f22eb5a7)
![Screenshot 2023-09-24 at 01 44 00](https://github.com/torinmb/mediapipe-touchdesigner/assets/117079301/4b8674d9-d145-4705-b2a2-65d5c0baa995)

**Comment by domisjustanumber** [comment]
Hi @duhglobe it looks like you may have downloaded the source code version.

Can you confirm you are using the files from release.zip on the Releases page? https://github.com/torinmb/mediapipe-touchdesigner/releases

**Comment by duhglobe** [comment]
Yes confirmed! I downloaded the release.zip file following your guide-tutorial.

**Comment by electroMedia666** [comment]
This happens for me as well. In fact, the MediaPipe.tox is empty upon restart. I definitely, 110%, downloaded the release and not the source code. I'm on TD 2022.33910, and latest Windows 11. Downloaded release.zip from https://github.com/torinmb/mediapipe-touchdesigner/releases/tag/v0.2.1

**Comment by duhglobe** [comment]
for installations or professional use this is a problem... do you think you can fix it?
thx so much <3
Andrea

**Comment by electroMedia666** [comment]
@domisjustanumber Thanks for taking some time from your vacation. I implemented the lines of code in issue #37 , but the problem persists, and nothing has appeared to change.
