### ISSUE TITLE
mediapip do not working no image

### ISSUE THREAD

**Issue by kungewan** [torinmb/mediapipe-touchdesigner#40]
![2](https://github.com/torinmb/mediapipe-touchdesigner/assets/145963689/2368f9e7-5eae-46f9-9bc7-fe643365b635)
![3](https://github.com/torinmb/mediapipe-touchdesigner/assets/145963689/d564c3f5-63d2-4825-957a-58c554691f06)
![4](https://github.com/torinmb/mediapipe-touchdesigner/assets/145963689/b5862520-c658-41c7-9bd6-bfa6792dad35)

windos10 rtx3060 laptop

**Comment by kungewan** [comment]
2022.33910

**Comment by domisjustanumber** [comment]
Hi @kungewan thanks for all the screen grabs.

To test, I would disable the Video Device In and select your webcam only in MediaPipe.

If that works, and you want to send a TOP to MediaPipe, you can then:
1. Install SpoutCam
2. Enable Video Device In
3. Select SpoutCam in the MediaPipe tox

You can then send any TOP you like to MediaPipe via the SyphonSpout Out TOP

**Comment by kungewan** [comment]
i use OBS as video device and its works  if i use laptop cam it does not work

**Comment by REEM-AR** [comment]
I have the same issue while using my laptop cam!

**Comment by REEM-AR** [comment]
I have the same issue, so what I did is:
- mediapipe > Laptop cam
- video device in> SpoutCam
this way you can use the tracker but can't view anything in videodevin till image_segmentation >> so no classify image/background remover, etc.

**Comment by domisjustanumber** [comment]
Hi @kungewan the [new v0.2.2 release](https://github.com/torinmb/mediapipe-touchdesigner/releases/tag/v0.2.2) fix your problem?

**Comment by domisjustanumber** [comment]
Sounds like this one might have fixed things, so closing this for now.
