### ISSUE TITLE
How to close the green line and red points of the track?

### ISSUE THREAD

**Issue by YUZURUonice** [torinmb/mediapipe-touchdesigner#47]
Hi, it is an amazing plung-in for TD, thank for sharing this！
I am a beginner of TD. I created a point following the movement of one finger point，and I wanted to use an over TOP to add the circle TOP above the video of realtime me. I connected the mediapipe directly to the over TOP，but I don't want the grean line and red dot still appearing there. Is there any method to do that excepting add one more camera but to use the realtime video in the mediapipe?

![Snipaste_2023-10-09_00-08-28](https://github.com/torinmb/mediapipe-touchdesigner/assets/147327311/9a09e0e6-6b7e-46df-af47-a3f8f372c0dd)
I connect the mediapipe to the over

![微信图片_20231009000944](https://github.com/torinmb/mediapipe-touchdesigner/assets/147327311/1c6f8b7b-e299-4f00-900d-982d051d37a0)
I want to delet the line and point

**Comment by torinmb** [comment]
Hey! The easiest way to hide those is to turn off "Show Overlays" on the MediaPipe component.
<img width="543" alt="Screenshot 2023-10-08 at 9 01 22 PM" src="https://github.com/torinmb/mediapipe-touchdesigner/assets/6014011/0274d8e4-480c-41b3-aa4e-a5d6c8eb08f5">
