### ISSUE TITLE
Top input

### ISSUE THREAD

**Issue by RayInst** [torinmb/mediapipe-touchdesigner#48]
Could it support other TOP input, not just limited to using a webcam?
Thanks

**Comment by domisjustanumber** [comment]
Hi @RayInst this is something we've been trying to figure out too! The issue we have is all of the MediaPipe ML is running in a web browser, so we've been playing with ways to get video into the web browser in a free/easy/low-latency way.

Right now the best method seems to be SpoutCam on Windows, or OBS Studio if you're on Mac.

**Comment by domisjustanumber** [comment]
It sounds like [this *might* be a solution](https://github.com/torinmb/mediapipe-touchdesigner/issues/64), so thought I'd link it here if you want to follow along. It's not a sure-fire thing, but I'm going to do some testing to see if I can get it to work.
