### ISSUE TITLE
Mediapipe tox is empty

### ISSUE THREAD

**Issue by joansc** [torinmb/mediapipe-touchdesigner#50]
Hello, Im trying your project for the first time (laptop windows 11 rtx 2070 with td version 2022.33910) and I cant get it to work. Followed all the steps (spout,...) and still it seems that the mediapipe tox is empty and dont know why... tried re-init, reimporting the tox, among other things without luck. Here some screenshots.

Thanks in advance,

Joan

![mediapipe_bug](https://github.com/torinmb/mediapipe-touchdesigner/assets/17720862/0c8c2e9a-dd42-475b-ad05-f5c5f1b1c2ff)
![Screenshot 2023-11-01 100632](https://github.com/torinmb/mediapipe-touchdesigner/assets/17720862/ea3fcc88-eb48-41c1-939f-e6d5f6380aed)

**Comment by domisjustanumber** [comment]
Thanks for the screen grab. I suspect this might not be working as you have something else running on the network port being used for the websocket communications.

If you change the port in the MediaPipe component from 9980 to something else (9981) that should fix it.

We also released a new version yesterday that eliminates the need for this port and has a bunch of other improvements https://github.com/torinmb/mediapipe-touchdesigner/releases/tag/v0.3.1

**Comment by k0seng** [comment]
Hi, I also just started and have the same issue, when opening a project file with an existing media pipe tox. When I zoom into the instance I don't see any operators, so maybe there's a problem with the loading process? 
Deleting the instance and importing the mediapipe tox again does the trick for me.

**Comment by torinmb** [comment]
Hey @joansc the only time I've seen this happen is if you open the .toe file from within the release.zip file without extracting the contents of the .zip file first. Can you double check you extracted the .zip?

**Comment by BrunoMariaTomas** [comment]
Hey @joansc  I have the same problem, I've extracted everything for sure from the .zip file (macBook Pro 2020 M1, TD 2022. 35320 )

**Comment by torinmb** [comment]
<img width="410" alt="Screenshot 2023-11-02 at 1 19 13 PM" src="https://github.com/torinmb/mediapipe-touchdesigner/assets/6014011/f29e45fd-0231-4721-86b6-85c46ab6d783">
Hey @joansc and @BrunoMariaTomas please make sure that you are downloading the release.zip. 
I'm able to reproduce the same error by opening the source.zip

**Comment by BrunoMariaTomas** [comment]
@torinmb I'm sorry but it’s still not working...

**Comment by torinmb** [comment]
@BrunoMariaTomas Since you're on a different OS I want to make sure we're exploring this as a separate issue. Can you share screen shots of your network and if there are any red Xs can you click on them and include them in the screen shot. Also what version of the plugin are you running the latest version of the MP plugin 0.3.2?

**Comment by torinmb** [comment]
Ok we found it!! We'll release an fix soon, but for now you can fix your network by doing the following:
1) Navigate to the MediaPipe component the Common tab 
2) Change the external tox path to ./toxes/MediaPipe.tox 
3) Click Re-Init Network
<img width="955" alt="Screenshot 2023-11-02 at 2 11 23 PM" src="https://github.com/torinmb/mediapipe-touchdesigner/assets/6014011/cd7bebc4-dc2c-4e4d-b820-7e94bb136571">

**Comment by torinmb** [comment]
I just pushed a quick fix in and added a new release.zip that fixes the issue. You can download the latest here: https://github.com/torinmb/mediapipe-touchdesigner/releases/tag/v0.3.2

It's still the same version number, but notice the release.zip was just updated

**Comment by BrunoMariaTomas** [comment]
@torinmb i've just installed an older version of the plugin and now it works!

**Comment by torinmb** [comment]
Can you test the latest since it has a fix?

**Comment by joansc** [comment]
Hello all, wow thanks for the fast response and debugging. I confirm that with the latest release it works straight out of the box. Thanks and congrats for this amazing tool!
