### ISSUE TITLE
OBS Virtual Camera Not Working

### ISSUE THREAD

**Issue by BrunoMariaTomas** [torinmb/mediapipe-touchdesigner#53]
I've followed correctly step by step the guide from the video [](https://www.youtube.com/watch?v=Cx4Ellaj6kk&ab_channel=TorinBlankensmith) but the virtual camera in TD doesn't show up, here some screenshoots. I've also tried to reset the camera multiple times or change the Websocket Port or the Mediapipe Port by 1 (ex. 3001 to 3002) but still not working. What I can do to fix this problem?
My device: MacBook Pro M1 2020, TD 2022.35320
<img width="1440" alt="Screenshot 2023-11-02 alle 19 57 34" src="https://github.com/torinmb/mediapipe-touchdesigner/assets/149709427/ba5023b4-f836-4642-b3fe-731b846695af">
<img width="1440" alt="Screenshot 2023-11-02 alle 19 57 53" src="https://github.com/torinmb/mediapipe-touchdesigner/assets/149709427/3789c6b3-8db3-4f28-ab2a-f85201fb938f">

**Comment by torinmb** [comment]
Can you verify the virtual webcam is working by opening up another application like [https://meet.google.com/ ](Google Meet) or Zoom, and setting the webcam to OBS. If it still shows the OBS background you may need to change some settings in OBS

**Comment by BrunoMariaTomas** [comment]
@torinmb thank you for your reply, I've just tried what you suggested me but as you can see the virtual camera works on Google Meet but in TD doesn’t, is there something I can do to fix this?

<img width="1440" alt="Screenshot 2023-11-02 alle 21 18 33" src="https://github.com/torinmb/mediapipe-touchdesigner/assets/149709427/350b8739-9054-4faf-8a02-c725b7a51498">

**Comment by torinmb** [comment]
Can you try changing the output resolution to 1280 x 720. Also another thing to test is setting a VideoDeviceInTOP in TouchDesigner to OBS and seeing if that loads.
<img width="1141" alt="Screenshot 2023-11-02 at 4 27 29 PM" src="https://github.com/torinmb/mediapipe-touchdesigner/assets/6014011/1ba59bdc-d64a-42ca-ac78-9c3493abea83">

**Comment by BrunoMariaTomas** [comment]
@torinmb I'm sorry to bothering you, I've just tried to change the Base(Canvas)Resolution down to 1280x720 but still don't work, I've also tried to use the VideoDeviceInTop in TD and still doesnt't work. 
I'm losing hope what i can do at this point?

<img width="1440" alt="Screenshot 2023-11-02 alle 21 45 50" src="https://github.com/torinmb/mediapipe-touchdesigner/assets/149709427/47003f52-2df2-418f-b7cd-aeb88db743d0">

**Comment by torinmb** [comment]
Hey no worries, I think we can safely say this is related to TouchDesigner or OBS and not the MediaPipe plugin. I'd try restarting your computer and starting up OBS and TD again. If the problem persists I'd recommend posting this as a bug on the TD forum. Maybe also try updating OBS. Hope this helps

**Comment by domisjustanumber** [comment]
I'm going to close this one as it's not an issue with the MP component.
