### ISSUE TITLE
No info from face_tracking blend_shapes 

### ISSUE THREAD

**Issue by tandryousee** [torinmb/mediapipe-touchdesigner#54]
Hi, 

I have this strange issue. Everything is working fine except the face_tracking blend_shape info. It can detect my face, but it doesn't register the blend_shape information, it's not showing the data at least. However, it does show the info from all the other tracking options.  

I have attached some screenshots. I'm curious to hear if there is something I'm missing, or something I might not be aware of. 

Im using a MacBook Pro M1, 16 GB memory with macOS Sonoma Version 14.0 
Touchdesigner 099 Non-Commercial 64-bit build 2023.11170 
Mediapipe release v0.3.2

Thanks :))) 

<img width="1246" alt="Screenshot 2023-11-06 at 12 52 22" src="https://github.com/torinmb/mediapipe-touchdesigner/assets/102984454/3d8dd8fc-38f6-40d8-ae4f-0df955c5de6c">

<img width="1059" alt="Screenshot 2023-11-06 at 12 50 33" src="https://github.com/torinmb/mediapipe-touchdesigner/assets/102984454/870f6947-297f-456e-b44d-e42a108c69a7">

**Comment by domisjustanumber** [comment]
Hi @tandryousee this is an odd one - I don't seem to be able to reproduce this. If the face mesh is being output, the blendshapes and transformation matrix also comes with it.

If you reload the component does it fix it at all and/or do you have any steps to reproduce it?

**Comment by domisjustanumber** [comment]
I found the issue - we were sending float instead of a boolean as the "export blend shapes" argument in Media Pipe. I've checked in changes that will be in the next release build

**Comment by domisjustanumber** [comment]
This got released in [v0.3.3](https://github.com/torinmb/mediapipe-touchdesigner/releases/tag/v0.3.3) so closing this issue
