### ISSUE TITLE
detecting 2 hands only

### ISSUE THREAD

**Issue by neildixon54321** [torinmb/mediapipe-touchdesigner#55]
Hi, I'm trying to detect more than 2 hands, but it's always detecting maximum 2 hands. If I set the hand count to 1 it still detects 2, tried setting it to detect 4 or 6 but still detecting 2.

Using Windows 11 Enterprise version 22H2 OS build 22621.2428.

Any suggestions? 

Thanks

**Comment by torinmb** [comment]
Hi @neildixon54321 the ML model form google only supports recognizing 2 hands max. you can see more details here: https://mediapipe-studio.webapps.google.com/studio/demo/gesture_recognizer. Hopefully in the future the'll support more hands.
