### ISSUE TITLE
face tracking sample issues

### ISSUE THREAD

**Issue by zhezzzzz** [torinmb/mediapipe-touchdesigner#57]
Hi, 
First, thank you for your great works! It helps me a lot.

I have an issue about the face tracking sample. 
It can detect my face, the face part and the texture part work well. However, the halo part does not work. It doesn’t move with my face and show nothing.  I'm curious to hear if there is something I'm missing.

(Also, the same problem with others, it does show the info from all the other tracking options.)

(By the way, I want to know how to change the resolution of the camera? I’m using the FaceTime HD camera of Mac, it shows error message but seems working to show my face. Do I need to change?)

I have attached the screenshot. 
<img width="778" alt="截屏2023-11-10 03 14 50" src="https://github.com/torinmb/mediapipe-touchdesigner/assets/81577423/f03b1473-fdaf-46d7-8d34-0435bcfc20b1">

——————————————
MacBook Pro (Intel, 2020) with macOS BigSur 11.7.10 
Touchdesigner 099 build 2022.35320
 Mediapipe release v0.3.2
——————————————

Thank u sooo much.

**Comment by domisjustanumber** [comment]
Hi @zhezzzzz thanks for the kind words and finding this bug! This issue got reported on https://github.com/torinmb/mediapipe-touchdesigner/issues/54 and I put some fixes in that will be in the next release build.
