### ISSUE TITLE
Mac 2020 m1 webcam

### ISSUE THREAD

**Issue by jongtaehwangbo** [torinmb/mediapipe-touchdesigner#58]
![Snapshot 02-12-2023 15:06](https://github.com/torinmb/mediapipe-touchdesigner/assets/152678906/f1ede0b8-601f-4ee6-b88b-5c381d306e6d)

T.T

**Comment by domisjustanumber** [comment]
Oh hey, sorry I didn't see this until now. Everything is actually working correctly, there was just a bug in the error message.

If you download [v0.3.3](https://github.com/torinmb/mediapipe-touchdesigner/releases/tag/v0.3.3) or later the error will go away :)
