### ISSUE TITLE
Webcam picture visible, but models not working

### ISSUE THREAD

**Issue by jbgbraun** [torinmb/mediapipe-touchdesigner#59]
Hello, 
thank you for this fantastic project first of all. 

I've had the _MediaPipe TouchDesigner.toe_ working for a short moment, but then changed the number of faces to detect, as suggested in the tutorial video. Ever since it does not work anymore. It shows the raw webcam picture in the MediaPipe component but it does not seem to be processed further. Tried restarting, loading again, etc. 

Windows 11, TouchDesigner 2023.11290, Release 0.3.3, Logitech BRIO webcam

Thanks for any hints!

**Comment by domisjustanumber** [comment]
FYI it sounds like the cause of this occasionally happening got tracked down, so we'll be making a fix in the next release. https://github.com/torinmb/mediapipe-touchdesigner/issues/60
