### ISSUE TITLE
Loading... message into MediaPipe

### ISSUE THREAD

**Issue by amyYZzz** [torinmb/mediapipe-touchdesigner#68]
Hi guys,

Do you know why I get a Loading... message into my MediaPipe?

![mediaPipe](https://github.com/torinmb/mediapipe-touchdesigner/assets/49841832/8e012a77-1fef-42c2-9747-9a49912b6a37)

I reseted also (clicked on pulse) with no effect. 
Windows OP: 
![image](https://github.com/torinmb/mediapipe-touchdesigner/assets/49841832/1ebee435-96c1-4437-898f-c106750f0962)

Version TD: 2023.11220 Experimental

Thanks for your help!
Ana

**Comment by domisjustanumber** [comment]
Hey @amyYZzz this usually happens when the webcam source you've selected doesn't have any video. Can you show the parameters panel for the MediaPipe component and which webcam you have selected?

**Comment by elrashidomer** [comment]
i have the sam issues Windows 11 
I used oak-d camera it work fine in ndi in
![Uploading Screenshot 2024-02-15 230430.png…]()

**Comment by domisjustanumber** [comment]
It looks like you have OBS Virtual Camera selected, is your OBS project set up to be 1280 x 720 in the Video settings?

**Comment by elrashidomer** [comment]
yes is selected in 1280x720 but the issues is same

**Comment by amyYZzz** [comment]
@domisjustanumber 
Interesting. I choose the camera from laptop:
![image](https://github.com/torinmb/mediapipe-touchdesigner/assets/49841832/86c099ab-27f8-41eb-85bc-66af3a27e898)


If I open another TD instance for example in parallel it works fine in the other project but MediaPipe not.

**Comment by domisjustanumber** [comment]
Hmm interesting. If the webcam opens in a Video Device In TOP and you can set it to 1280 x 720 with 25 or higher fps it should just work.

The other reason it doesn't work can be if you have more than one process trying to play the webcam video. Most only allow 1 stream at a time.

Otherwise I've seen the component just not work, then I save, restart TD and it works again... I haven't figured out why.

**Comment by Prakhar-Bhartiya-Madlab** [comment]
Hey @amyYZzz, I also had similar issue where sometime MediaPipe.tox doesn't recognize my available cameras or doesn't get feed from the camera even if i open and close my touchdesigner project multiple times.  One solution worked for me is to delete the MediaPipe.tox, and re import it. I believe it resets it. Hope this works out for you!

**Comment by domisjustanumber** [comment]
As it's been a couple of weeks, I'm going to close this one, but please re-open it if you have any further info on the issue.
