### ISSUE TITLE
Hands "Max Number of Hands" selection not working

### ISSUE THREAD

**Issue by ethanproia** [torinmb/mediapipe-touchdesigner#70]
Despite setting Max Number of Hands param to 1, both hands still detected and sending data to CHOPs.

<img width="1920" alt="max number hands error" src="https://github.com/torinmb/mediapipe-touchdesigner/assets/47930611/2c1ba115-5e8a-46bb-be03-a616b0892386">

**Comment by domisjustanumber** [comment]
Hey @ethanproia thanks for reporting this - I had a typo in the parameter name, so have fixed it for future releases.

If you want to fix it in the mean-time, you can do so in TD.

1. Right-click on the MediaPipe component and select "Customize Component..."
2. Go to the `Hands` section
3. Find `Hnumhands` and change it to `Gnumhands`

![image](https://github.com/torinmb/mediapipe-touchdesigner/assets/36455793/b0cf6536-bbaf-48d3-b379-d27a11685769)

**Comment by domisjustanumber** [comment]
Annnd it took a while, but this is now fixed! https://github.com/torinmb/mediapipe-touchdesigner/releases/tag/v0.4.3
