### ISSUE TITLE
Camera Feed

### ISSUE THREAD

**Issue by CarAustin** [torinmb/mediapipe-touchdesigner#73]
Hi, I can't wait to use this, except my Mac camera feed isn't showing on the media pipe when I select FaceTime HD camera. I've tried the pulse button and made sure that my Mac allows Touch Designer in the security settings. Please advise as to what I should do next.  I have a feeling TD is trying to choose the webcam OBS virtual and T's phone. Neither of which Im familiar with. 

Thanks

<img width="1440" alt="media pipe" src="https://github.com/torinmb/mediapipe-touchdesigner/assets/129034195/9bac626f-6c0b-41b3-8b4d-02cd5af67f2f">

<img width="516" alt="Screenshot 2024-03-21 at 3 17 14 pm" src="https://github.com/torinmb/mediapipe-touchdesigner/assets/129034195/45a45344-abef-487f-a6b8-d7e0d5891fd0">

**Comment by CarAustin** [comment]
Hey, thanks for your reply. It's sorted. It was a file pathway problem.  Now the fun begins! Thanks

**Comment by domisjustanumber** [comment]
Glad you got it working!
