### ISSUE TITLE
Latest Release issues  

### ISSUE THREAD

**Issue by lifeonmod** [torinmb/mediapipe-touchdesigner#74]
Noticed that older versions of mediapipe still work  but  after each save  and  file  rename TD will fail to load all the media pipe assets   and  whole networks  are  gone inside the mideapipe window  , including operator IN and OUT nodes. 
could this be due to the new  release update ? 
it was saving a and reloading  fine 2 weeks ago last release update was 7 days ago?  
images below of the standard network vs  the missing one , 

im teaching a class MAY 11TH  using touchdesinger and mediapipe was a big part of the  workshop. 

please get back to me  

![TouchDesigner 2023 11600_ C__Users_kabug_Downloads_MediaPipe-20240322T013000Z-001_MediaPipe_MediaPipedown TouchDesigner 3 toe 24-03-29 02_55_23 AM](https://github.com/torinmb/mediapipe-touchdesigner/assets/69732732/8115faf6-67c9-4434-903c-f52fcc23063f)
![TouchDesigner 2023 11600_ C__Users_kabug_Desktop_MediaPipedown AUGEMMIX TouchDesigner 16 toe 24-03-29 03_04_53 AM](https://github.com/torinmb/mediapipe-touchdesigner/assets/69732732/6cd28f5a-5892-439d-80ae-9ccb8650fef9)
![TouchDesigner 2023 11600_ C__Users_kabug_Desktop_MediaPipedown AUGEMMIX TouchDesigner 16 toe 24-03-29 02_49_17 AM](https://github.com/torinmb/mediapipe-touchdesigner/assets/69732732/78e183e0-93c5-4aa4-8347-75fc7e6f5d83)

**Comment by domisjustanumber** [comment]
Hey @lifeonmod if you're saving to a new folder/location, you also need to include the toxes folder and all the tox files in it.

![Screenshot 2024-03-29 104520](https://github.com/torinmb/mediapipe-touchdesigner/assets/36455793/fec42020-5258-4137-8832-018a04d0502e)
![Screenshot 2024-03-29 104846](https://github.com/torinmb/mediapipe-touchdesigner/assets/36455793/07602bed-1d05-481f-bfb4-ab225669aaa5)

**Comment by lifeonmod** [comment]
Thank you for the speedy reply 
The suggestion worked perfectly. 

I will be looking to  reload the external toxes during each boot up. 

Thank you
-LoM
