### ISSUE TITLE
MediaPipe Stuck on LOADING

### ISSUE THREAD

**Issue by CHNGZchanges** [torinmb/mediapipe-touchdesigner#79]
Hey, downloaded MediaPipe today and was super excited to try it out with the different effects I've made but after importing the tox file into TD, it gets stuck on loading and no matter what I do the issue persists. I'm running TD on Windows 11 Pro 10.0.22621 Build 22621 and at first my TD was a little outdated, it was Version 2022.32050 and so I tried updating my TD to Version 2023.11600 and still no difference. 
Another thing is that MediaPipe can't recognize my webcam. I took a screenshot of the options I have to choose from for the webcam.
![Screenshot 2024-04-16 195819](https://github.com/torinmb/mediapipe-touchdesigner/assets/167229910/14015719-cd4d-4676-bed1-5e125dd656da)
It's worth mentioning before this version of MediaPipe (v0.4.2), I had downloaded an earlier version of it and I had the same problem except that the dropdown webcam list had different options but still none of them was my webcam and it was still just stuck on loading.
I also did try Spout with a Video Device In TOP (my webcam selected) connected to it following all the steps Dom mentioned in the Youtube video and that still did not work.
I also had an external camera set up in the OBS and then selected OBS Virtual Camera from the webcam parameter (cause that option did exist) and still no difference.
I'm also getting no errors so I'm absolutely clueless about what might be the problem here.

**Comment by domisjustanumber** [comment]
Hey @CHNGZchanges sorry to hear you're having issues getting it working. Can you confirm you're running the version from the release.zip?

**Comment by CHNGZchanges** [comment]
Yes, I am!
I used the .tox file from release.zip and also tried the .toe file

**Comment by CHNGZchanges** [comment]
@domisjustanumber I'd appreciate it if you could share with me any recommendations that comes to your mind

**Comment by domisjustanumber** [comment]
Hey @CHNGZchanges it looks like the plugin isn't loading at all, so it's not updating the list of webcams.

Do you have all the .tox files in the original folder structure?
If you open the text port, does it have any error messages?

The only other thing I can think of might be some kind of antivirus blocking the network port the plugin is using (in your screenshot, port 2213). You could try (temporarily!) disabling any antivirus or firewall software you have running to see if that fixes it.

**Comment by CHNGZchanges** [comment]
Thank you for your response @domisjustanumber 
I'm not exactly sure what you mean by having all the .tox files in the original folder structure. I'd appreciate if you could elaborate more.
I do have a .toe file and a folder named toxes with 10 .tox files inside from the release.zip I downloaded.
I tried opening the .toe file after turning off my antivirus and firewall (Defender on Windows 11) and it did't make a difference.
Also here's a screenshot of my textport from the .toe file. Seems like there are no errors but I'm not sure if everything's alright here. That's why I took a screenshot.
![Screenshot 2024-04-24 112212](https://github.com/torinmb/mediapipe-touchdesigner/assets/167229910/3eae793d-ce27-4bf2-a954-4a06fdb9db4e)

**Comment by CHNGZchanges** [comment]
@domisjustanumber Hello again, I just realized the issue was due to a software I had installed before for an external camera. I uninstalled it and everything works as it should now. Just wanted to thank you and Torin again for this wonderful plugin and also thank you for your help with the issue.

**Comment by domisjustanumber** [comment]
Oh that's great news, I'm glad you figured it out!
