### ISSUE TITLE
Question on multiple Pose Tracking

### ISSUE THREAD

**Issue by lucaperrin** [torinmb/mediapipe-touchdesigner#82]
Hi there,

When using the pose_tracking module on a TOP containing more than one “human” to track, is there a way to display the confidence level of each human? Or a way to “choose” or select the human I want to track based on the confidence level? 

I’ve noticed the confidence parameters under the Pose settings of the MediaPipe comp but they don’t seem to be enough for what I am trying to achieve. 

Thanks in advance!

**Comment by domisjustanumber** [comment]
Hey @lucaperrin unfortunately not really - MediaPipe isn't very good at multi-pose tracking. In other projects I've found https://github.com/open-mmlab/mmpose/tree/main/projects/rtmo to be amazingly good for multi-pose tracking, but it's a Python library that you'll need to integrate into TouchDesigner yourself, so not super user-friendly right now.
