### ISSUE TITLE
Hand tracking overlap

### ISSUE THREAD

**Issue by manami000** [torinmb/mediapipe-touchdesigner#83]
I am fairly new to TD, but I am having a problem with hand tracking, as it seems like a hand gets registered with more points than it should have. This is causing me issues with recognizing gestures and it doesn't register more than one hand at the time.

![Screenshot 2024-05-16 180458](https://github.com/torinmb/mediapipe-touchdesigner/assets/90057527/5fcc31e1-fe11-4fe9-ab84-77cc8743d342)

![Screenshot 2024-05-16 204048](https://github.com/torinmb/mediapipe-touchdesigner/assets/90057527/13cc8ede-cf16-4f17-b8d5-055cb46acb68)

**Comment by zesemotion** [comment]
Hi!
How you resolve it? I'm having the same problem

**Comment by manami000** [comment]
> Hi! How you resolve it? I'm having the same problem

Hello, yes so the problem were the fps, i had them set at 30 but they should've been at 60. Once i did this it got back to normal!

**Comment by zesemotion** [comment]
> > Hi! How you resolve it? I'm having the same problem
> 
> Hello, yes so the problem were the fps, i had them set at 30 but they should've been at 60. Once i did this it got back to normal!

Thanks!!! I was getting crazy hahah
