### ISSUE TITLE
First Detection of hand is always on the left.

### ISSUE THREAD

**Issue by foong** [torinmb/mediapipe-touchdesigner#86]
Im having issue where the first instance of a detected hand is always "h1" and always "left hand" regardless if i am using my left or right hand. the second detected hand will always be "h2" and always "right hand"
<img width="1512" alt="Screenshot 2024-05-30 at 4 46 43 PM" src="https://github.com/torinmb/mediapipe-touchdesigner/assets/12502272/4fb1eee6-2c0e-447b-80fa-9586465dfe4f">
<img width="1512" alt="Screenshot 2024-05-30 at 4 46 34 PM" src="https://github.com/torinmb/mediapipe-touchdesigner/assets/12502272/480140ee-1d98-40a4-bdf0-04e80b8780bc">

**Comment by domisjustanumber** [comment]
Hey! Wow sorry it took so long to get back to you. This was an interesting one to dig into - h1 and h2 are simply "first hand detected and second hand detected" - they could be 2 left hands or 2 right hands.

However, MediaPipe does output a score of how confident it is about the detected hand being left or right. I've just added 4 extra channels to the Helpers CHOP that give you the amount of "Rightness" or "Leftness" confidence MediaPipe has for each detected hand.

It'll be in the next release :)

![image](https://github.com/user-attachments/assets/356f2a1e-d99a-46db-9924-1c80f9f8af2c)

**Comment by domisjustanumber** [comment]
Now released! https://github.com/torinmb/mediapipe-touchdesigner/releases/tag/v0.4.3
