### ISSUE TITLE
SpoutCam connection failed

### ISSUE THREAD

**Issue by mericostx** [torinmb/mediapipe-touchdesigner#87]
Good morning everyone, 

first of all thanks Dom and Torin for what you are doing for the community <333

i have an issue trying to connect SpoutCam with the Mediapipe project. The "video device in TOP" detects my webcam, but the "syphonspoutout TOP" is not working. And then the "mediapipe container" seems to have an issue also. 

 I have followed exactly what Dom did in the tutorial.  I'm working with Intel Nuc 13 Pro with a 13th Gen Intel Core Processor, the latest file you have updated and TD 2023.11760. 

Thanks :)))

![Screenshot 2024-05-31 085421](https://github.com/torinmb/mediapipe-touchdesigner/assets/132358388/cd32aa40-7a5b-4b04-a399-673f0f4e9418)

![Screenshot 2024-05-31 090634](https://github.com/torinmb/mediapipe-touchdesigner/assets/132358388/3e76a365-3fd5-4d5a-8b98-cb53e8af5329)

**Comment by lucaperrin** [comment]
Def a strange one...
Might seem obvious but have you double checked that you have downloaded the latest release on GitHub and that your file is located in the same folder as the "toxes" folder?

**Comment by domisjustanumber** [comment]
Yeah, that looks like it's something to do with Spout and your system. As @lucaperrin says, I'd recommend making sure you have the latest TD, graphics drivers, and SpoutCam and see if any of them help.

**Comment by treybradley** [comment]
Also having an issue getting spoutcam into touchdesigner but with a different error saying 'webcam failed to start.." (screenshot attached). Running on Windows 11. For context, everything was working great for the past few weeks but randomly getting this error now. Have tried troubleshooting in a few different ways:

- removing/re-installing spoutcam
- registering/un-registering spout cam and playing with the settings
- pulse/resetting the main component tox
- playing with the pixel format going into my syphonspoutout top
- switching the webcam source on the main component tox from NotchCam to SpoutCam
- trying previous versions of this project and spoutcam

each of these methods have had success at one time or another in getting spout into the tox. now i have things running again with a new spoutcam download and new release download, however i still see this error message on the component tox and its kinda hit or miss when i close/re-open my projects if it works. happy to share any more details about my machine/set up.

And lastly, seconding the first comment - thank you (Dom and Torin) and the community so much for supporting creative people with your incredible work

![image](https://github.com/user-attachments/assets/122975bb-aa12-429b-86d8-567fb25e8583)

**Comment by domisjustanumber** [comment]
I have a feeling this is due to a race condition in my js code that starts the webcam - essentially it (sometimes) tries to start the webcam before it's found the correct one, and it throws, but doesn't remove the error. It might be that this is worse with SpoutCam for some reason, but not sure where/how to fix it.

For now, you can ignore the error if it actually works

**Comment by benjaminsnapir** [comment]
Hi! I have tried to use MediaPipe but for some reason it doesn't read my Spoutcam. The problem can't be in the Spoutcam itself because if I send a image through Spoutcam to a videdevicein, it works just fine. Some how when I try to send it to Mediapipe, it sipmly does nothing? Does anyone have any suggestions on what to do? :) I would appreciate it greatly

**Comment by lucaperrin** [comment]
@benjaminsnapir Have you tried with OBS virtual camera instead ?

**Comment by domisjustanumber** [comment]
I'm going to close this as it's not been updated in a long time, but feel free to re-open if you have any follow-ups.
