### ISSUE TITLE
Slow File Save: Turn on "Enable External .tox" on MediaPipe by Default

### ISSUE THREAD

**Issue by torinmb** [torinmb/mediapipe-touchdesigner#90]
In newer versions of TD this is turned off. If someone drags the MP.tox into their project and tries saving it takes foreverrrr to save because it's encoding the whole MP tox in the .toe. Enabling externalization by default will help a lot of people.

For anyone seeing this you can fix the slow file saves by turning on "Enable External .tox" in the common tab of the MediaPipe container. Make sure when you drag the MediaPipe.tox into your project it's next to your .toe file (similar to how you keep movie files in the same folder as your project)
<img width="1076" alt="Screenshot 2024-06-12 at 3 33 33 PM" src="https://github.com/torinmb/mediapipe-touchdesigner/assets/6014011/1be3c043-a6a5-46da-b5de-0919b92bef8c">

**Comment by domisjustanumber** [comment]
I think this is a bug in TD 2023 (or at least 2023.11880) - saving a tox with the "Enable External .tox" flag set does correctly restore that flag when you drag the tox into a new TD project in TD 2022, but it does not in TD 2023.

I've tried re-saving the .tox file in TD 2023 and it doesn't make any difference, so I think it's a TD 2023 bug.

**Comment by domisjustanumber** [comment]
This indeed appears to be a "feature" of 2023 TouchDesigner, so I'll add a note to to Readme to let people know... although I suspect nobody will read it 😆 

https://derivative.ca/community-post/word-about-external-files-202310k-builds/68166

![image](https://github.com/user-attachments/assets/a1c7990d-a04f-4ee1-af44-c43cce988179)

**Comment by domisjustanumber** [comment]
Going to close this one as it's a TD bug and I added this lovely screencap to the release notes
