### ISSUE TITLE
no outputs on Mediapipe :( 

### ISSUE THREAD

**Issue by chasseiffert** [torinmb/mediapipe-touchdesigner#94]
HI I'm running windows 11 and using version 2023.11880. and after downloading the release.zip and opening the MediaPipe included I was presented with a non working setup with no outputs or lines  from the mediapipe node. 
I asked chatgpt and it said I needed to pip install the python extension into touchdesigner. But i don't know how to do that or if that is even what to do 
here is the photo 
![image](https://github.com/user-attachments/assets/fb157431-0c22-4765-992c-5feae23346eb)
![Screenshot 2024-07-28 213001](https://github.com/user-attachments/assets/08f09c18-ba88-4581-b397-030a31080f7b)
if you need anything else please ask

**Comment by torinmb** [comment]
This usually happens when you try to open the files from the .zip without
extracting the files first. Make sure you extract the .zip and try opening
it again

**Comment by domisjustanumber** [comment]
Closing this as it's been a couple of weeks, but please re-open if you're still having issues.
