### ISSUE TITLE
Problem with Camera

### ISSUE THREAD

**Issue by Echeverry03** [torinmb/mediapipe-touchdesigner#99]
![image](https://github.com/user-attachments/assets/90979bb3-8053-4d24-8e65-812c58614e22)
i need help with this problem please. I use Windows 11 and TouchDesigner version 2023.11880 web Installer

**Comment by Echeverry03** [comment]
![image](https://github.com/user-attachments/assets/0f901285-cc7a-451e-b52d-fb7f2cf119b2)
why i don't see a input or output of the window in the MediaPipe?

**Comment by domisjustanumber** [comment]
Did you download the release.zip and extract all the files into a folder?

The example .toe file also needs the toxes folder and all of the .tox files in it to work.

**Comment by stefanopasseri** [comment]
Hi, thanks again for this amazing plugin! I'm using it in my TouchDesigner class but two of my students are running into this same issue. They both have working webcams and active internet connections. When they run the plugin (downloaded as per you instructions) the main COMP is empty. The toxes and the toe file they are working with are in the same folder. Any guidance you can share would be incredibly helpful. Thank you so much! Stefano

**Comment by torinmb** [comment]
@stefanopasseri I've only seen this happen when the project is opened from within the .zip file without extracting the file. Could you make sure the .zip is extracted first? It's really easy to skip this step on Windows.

**Comment by stefanopasseri** [comment]
Thanks, Torin! I'll pass this along to my students and will let you know. :)

**Comment by domisjustanumber** [comment]
I'm going to close this as it's not been updated in a long time, but feel free to re-open if you have any follow-ups.
